### ISSUE TITLE
 ** (EXIT) shutdown: failed to start child: Openstex.Adapters.Rackspace.Cloudfiles.Config         ** (EXIT) an exception was raised:             ** (MatchError) no match of right hand side value: {:error, %HTTPipe.Conn{adapter: HTTPipe.Adapters.Hackney, adapter_options: [timeout: 30000, recv_timeout: 30000], error: %HTTPipe.Adapters.Hackney.RequestError{message: "Hackney encountered an error while attempting to communicate with\nthe server. The reason given was:\n\ntimeout\n"}

### ISSUE THREAD

**Issue by thomasdola** [stephenmoloney/openstex#11]
Getting this error in case of no internet on my local development machine...
From what i have seen it makes a request to the rackspace server any time the app boots...

` ** (EXIT) shutdown: failed to start child: Openstex.Adapters.Rackspace.Cloudfiles.Config
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, %HTTPipe.Conn{adapter: HTTPipe.Adapters.Hackney, adapter_options: [timeout: 30000, recv_timeout: 30000], error: %HTTPipe.Adapters.Hackney.RequestError{message: "Hackney encountered an error while attempting to communicate with\nthe server. The reason given was:\n\ntimeout\n"}`

Any help?

**Comment by stephenmoloney** [comment]
Hi there, 
I use openstex with OVH (who uses openstack) and i've had limited use of the cloudfiles adapter.

I've also been on a ***massive*** hiatus from programming (in the order of months).

That said, I will be back to my desk in 2 weeks time - This issue will be top of my list

Hope that will of use by then?

On the surface seems like a timeout issue - should be relatively easy to fix.

**Comment by stephenmoloney** [comment]
Closing as should be a problem with openstex_adapters_rackspace and not openstex itself.

Moved to [issue](https://github.com/stephenmoloney/openstex_adapters_rackspace/issues/1)
